//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: warp.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `WarpClient`, then call methods of this protocol to make API calls.
public protocol WarpClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: WarpClientInterceptorFactoryProtocol? { get }

  func checkDuplexConnection(
    _ request: LookupName,
    callOptions: CallOptions?
  ) -> UnaryCall<LookupName, HaveDuplex>

  func waitingForDuplex(
    _ request: LookupName,
    callOptions: CallOptions?
  ) -> UnaryCall<LookupName, HaveDuplex>

  func getRemoteMachineInfo(
    _ request: LookupName,
    callOptions: CallOptions?
  ) -> UnaryCall<LookupName, RemoteMachineInfo>

  func getRemoteMachineAvatar(
    _ request: LookupName,
    callOptions: CallOptions?,
    handler: @escaping (RemoteMachineAvatar) -> Void
  ) -> ServerStreamingCall<LookupName, RemoteMachineAvatar>

  func processTransferOpRequest(
    _ request: TransferOpRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<TransferOpRequest, VoidType>

  func pauseTransferOp(
    _ request: OpInfo,
    callOptions: CallOptions?
  ) -> UnaryCall<OpInfo, VoidType>

  func startTransfer(
    _ request: OpInfo,
    callOptions: CallOptions?,
    handler: @escaping (FileChunk) -> Void
  ) -> ServerStreamingCall<OpInfo, FileChunk>

  func cancelTransferOpRequest(
    _ request: OpInfo,
    callOptions: CallOptions?
  ) -> UnaryCall<OpInfo, VoidType>

  func stopTransfer(
    _ request: StopInfo,
    callOptions: CallOptions?
  ) -> UnaryCall<StopInfo, VoidType>

  func ping(
    _ request: LookupName,
    callOptions: CallOptions?
  ) -> UnaryCall<LookupName, VoidType>
}

extension WarpClientProtocol {
  public var serviceName: String {
    return "Warp"
  }

  /// Sender methods
  /// api v1 duplex method (ping style)
  ///
  /// - Parameters:
  ///   - request: Request to send to CheckDuplexConnection.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func checkDuplexConnection(
    _ request: LookupName,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<LookupName, HaveDuplex> {
    return self.makeUnaryCall(
      path: "/Warp/CheckDuplexConnection",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckDuplexConnectionInterceptors() ?? []
    )
  }

  /// api v2 duplex method (block/future)
  ///
  /// - Parameters:
  ///   - request: Request to send to WaitingForDuplex.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func waitingForDuplex(
    _ request: LookupName,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<LookupName, HaveDuplex> {
    return self.makeUnaryCall(
      path: "/Warp/WaitingForDuplex",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWaitingForDuplexInterceptors() ?? []
    )
  }

  /// Unary call to GetRemoteMachineInfo
  ///
  /// - Parameters:
  ///   - request: Request to send to GetRemoteMachineInfo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getRemoteMachineInfo(
    _ request: LookupName,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<LookupName, RemoteMachineInfo> {
    return self.makeUnaryCall(
      path: "/Warp/GetRemoteMachineInfo",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetRemoteMachineInfoInterceptors() ?? []
    )
  }

  /// Server streaming call to GetRemoteMachineAvatar
  ///
  /// - Parameters:
  ///   - request: Request to send to GetRemoteMachineAvatar.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func getRemoteMachineAvatar(
    _ request: LookupName,
    callOptions: CallOptions? = nil,
    handler: @escaping (RemoteMachineAvatar) -> Void
  ) -> ServerStreamingCall<LookupName, RemoteMachineAvatar> {
    return self.makeServerStreamingCall(
      path: "/Warp/GetRemoteMachineAvatar",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetRemoteMachineAvatarInterceptors() ?? [],
      handler: handler
    )
  }

  /// Unary call to ProcessTransferOpRequest
  ///
  /// - Parameters:
  ///   - request: Request to send to ProcessTransferOpRequest.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func processTransferOpRequest(
    _ request: TransferOpRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<TransferOpRequest, VoidType> {
    return self.makeUnaryCall(
      path: "/Warp/ProcessTransferOpRequest",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeProcessTransferOpRequestInterceptors() ?? []
    )
  }

  /// Unary call to PauseTransferOp
  ///
  /// - Parameters:
  ///   - request: Request to send to PauseTransferOp.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func pauseTransferOp(
    _ request: OpInfo,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<OpInfo, VoidType> {
    return self.makeUnaryCall(
      path: "/Warp/PauseTransferOp",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePauseTransferOpInterceptors() ?? []
    )
  }

  /// Receiver methods
  ///
  /// - Parameters:
  ///   - request: Request to send to StartTransfer.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func startTransfer(
    _ request: OpInfo,
    callOptions: CallOptions? = nil,
    handler: @escaping (FileChunk) -> Void
  ) -> ServerStreamingCall<OpInfo, FileChunk> {
    return self.makeServerStreamingCall(
      path: "/Warp/StartTransfer",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStartTransferInterceptors() ?? [],
      handler: handler
    )
  }

  /// Both
  ///
  /// - Parameters:
  ///   - request: Request to send to CancelTransferOpRequest.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func cancelTransferOpRequest(
    _ request: OpInfo,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<OpInfo, VoidType> {
    return self.makeUnaryCall(
      path: "/Warp/CancelTransferOpRequest",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCancelTransferOpRequestInterceptors() ?? []
    )
  }

  /// Unary call to StopTransfer
  ///
  /// - Parameters:
  ///   - request: Request to send to StopTransfer.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func stopTransfer(
    _ request: StopInfo,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<StopInfo, VoidType> {
    return self.makeUnaryCall(
      path: "/Warp/StopTransfer",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStopTransferInterceptors() ?? []
    )
  }

  /// Unary call to Ping
  ///
  /// - Parameters:
  ///   - request: Request to send to Ping.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func ping(
    _ request: LookupName,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<LookupName, VoidType> {
    return self.makeUnaryCall(
      path: "/Warp/Ping",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePingInterceptors() ?? []
    )
  }
}

public protocol WarpClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'checkDuplexConnection'.
  func makeCheckDuplexConnectionInterceptors() -> [ClientInterceptor<LookupName, HaveDuplex>]

  /// - Returns: Interceptors to use when invoking 'waitingForDuplex'.
  func makeWaitingForDuplexInterceptors() -> [ClientInterceptor<LookupName, HaveDuplex>]

  /// - Returns: Interceptors to use when invoking 'getRemoteMachineInfo'.
  func makeGetRemoteMachineInfoInterceptors() -> [ClientInterceptor<LookupName, RemoteMachineInfo>]

  /// - Returns: Interceptors to use when invoking 'getRemoteMachineAvatar'.
  func makeGetRemoteMachineAvatarInterceptors() -> [ClientInterceptor<LookupName, RemoteMachineAvatar>]

  /// - Returns: Interceptors to use when invoking 'processTransferOpRequest'.
  func makeProcessTransferOpRequestInterceptors() -> [ClientInterceptor<TransferOpRequest, VoidType>]

  /// - Returns: Interceptors to use when invoking 'pauseTransferOp'.
  func makePauseTransferOpInterceptors() -> [ClientInterceptor<OpInfo, VoidType>]

  /// - Returns: Interceptors to use when invoking 'startTransfer'.
  func makeStartTransferInterceptors() -> [ClientInterceptor<OpInfo, FileChunk>]

  /// - Returns: Interceptors to use when invoking 'cancelTransferOpRequest'.
  func makeCancelTransferOpRequestInterceptors() -> [ClientInterceptor<OpInfo, VoidType>]

  /// - Returns: Interceptors to use when invoking 'stopTransfer'.
  func makeStopTransferInterceptors() -> [ClientInterceptor<StopInfo, VoidType>]

  /// - Returns: Interceptors to use when invoking 'ping'.
  func makePingInterceptors() -> [ClientInterceptor<LookupName, VoidType>]
}

public final class WarpClient: WarpClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: WarpClientInterceptorFactoryProtocol?

  /// Creates a client for the Warp service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: WarpClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Usage: instantiate `WarpRegistrationClient`, then call methods of this protocol to make API calls.
public protocol WarpRegistrationClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: WarpRegistrationClientInterceptorFactoryProtocol? { get }

  func requestCertificate(
    _ request: RegRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<RegRequest, RegResponse>
}

extension WarpRegistrationClientProtocol {
  public var serviceName: String {
    return "WarpRegistration"
  }

  /// Unary call to RequestCertificate
  ///
  /// - Parameters:
  ///   - request: Request to send to RequestCertificate.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func requestCertificate(
    _ request: RegRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<RegRequest, RegResponse> {
    return self.makeUnaryCall(
      path: "/WarpRegistration/RequestCertificate",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRequestCertificateInterceptors() ?? []
    )
  }
}

public protocol WarpRegistrationClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'requestCertificate'.
  func makeRequestCertificateInterceptors() -> [ClientInterceptor<RegRequest, RegResponse>]
}

public final class WarpRegistrationClient: WarpRegistrationClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: WarpRegistrationClientInterceptorFactoryProtocol?

  /// Creates a client for the WarpRegistration service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: WarpRegistrationClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol WarpProvider: CallHandlerProvider {
  var interceptors: WarpServerInterceptorFactoryProtocol? { get }

  /// Sender methods
  /// api v1 duplex method (ping style)
  func checkDuplexConnection(request: LookupName, context: StatusOnlyCallContext) -> EventLoopFuture<HaveDuplex>

  /// api v2 duplex method (block/future)
  func waitingForDuplex(request: LookupName, context: StatusOnlyCallContext) -> EventLoopFuture<HaveDuplex>

  func getRemoteMachineInfo(request: LookupName, context: StatusOnlyCallContext) -> EventLoopFuture<RemoteMachineInfo>

  func getRemoteMachineAvatar(request: LookupName, context: StreamingResponseCallContext<RemoteMachineAvatar>) -> EventLoopFuture<GRPCStatus>

  func processTransferOpRequest(request: TransferOpRequest, context: StatusOnlyCallContext) -> EventLoopFuture<VoidType>

  func pauseTransferOp(request: OpInfo, context: StatusOnlyCallContext) -> EventLoopFuture<VoidType>

  /// Receiver methods
  func startTransfer(request: OpInfo, context: StreamingResponseCallContext<FileChunk>) -> EventLoopFuture<GRPCStatus>

  /// Both
  func cancelTransferOpRequest(request: OpInfo, context: StatusOnlyCallContext) -> EventLoopFuture<VoidType>

  func stopTransfer(request: StopInfo, context: StatusOnlyCallContext) -> EventLoopFuture<VoidType>

  func ping(request: LookupName, context: StatusOnlyCallContext) -> EventLoopFuture<VoidType>
}

extension WarpProvider {
  public var serviceName: Substring { return "Warp" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CheckDuplexConnection":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<LookupName>(),
        responseSerializer: ProtobufSerializer<HaveDuplex>(),
        interceptors: self.interceptors?.makeCheckDuplexConnectionInterceptors() ?? [],
        userFunction: self.checkDuplexConnection(request:context:)
      )

    case "WaitingForDuplex":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<LookupName>(),
        responseSerializer: ProtobufSerializer<HaveDuplex>(),
        interceptors: self.interceptors?.makeWaitingForDuplexInterceptors() ?? [],
        userFunction: self.waitingForDuplex(request:context:)
      )

    case "GetRemoteMachineInfo":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<LookupName>(),
        responseSerializer: ProtobufSerializer<RemoteMachineInfo>(),
        interceptors: self.interceptors?.makeGetRemoteMachineInfoInterceptors() ?? [],
        userFunction: self.getRemoteMachineInfo(request:context:)
      )

    case "GetRemoteMachineAvatar":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<LookupName>(),
        responseSerializer: ProtobufSerializer<RemoteMachineAvatar>(),
        interceptors: self.interceptors?.makeGetRemoteMachineAvatarInterceptors() ?? [],
        userFunction: self.getRemoteMachineAvatar(request:context:)
      )

    case "ProcessTransferOpRequest":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<TransferOpRequest>(),
        responseSerializer: ProtobufSerializer<VoidType>(),
        interceptors: self.interceptors?.makeProcessTransferOpRequestInterceptors() ?? [],
        userFunction: self.processTransferOpRequest(request:context:)
      )

    case "PauseTransferOp":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<OpInfo>(),
        responseSerializer: ProtobufSerializer<VoidType>(),
        interceptors: self.interceptors?.makePauseTransferOpInterceptors() ?? [],
        userFunction: self.pauseTransferOp(request:context:)
      )

    case "StartTransfer":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<OpInfo>(),
        responseSerializer: ProtobufSerializer<FileChunk>(),
        interceptors: self.interceptors?.makeStartTransferInterceptors() ?? [],
        userFunction: self.startTransfer(request:context:)
      )

    case "CancelTransferOpRequest":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<OpInfo>(),
        responseSerializer: ProtobufSerializer<VoidType>(),
        interceptors: self.interceptors?.makeCancelTransferOpRequestInterceptors() ?? [],
        userFunction: self.cancelTransferOpRequest(request:context:)
      )

    case "StopTransfer":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<StopInfo>(),
        responseSerializer: ProtobufSerializer<VoidType>(),
        interceptors: self.interceptors?.makeStopTransferInterceptors() ?? [],
        userFunction: self.stopTransfer(request:context:)
      )

    case "Ping":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<LookupName>(),
        responseSerializer: ProtobufSerializer<VoidType>(),
        interceptors: self.interceptors?.makePingInterceptors() ?? [],
        userFunction: self.ping(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol WarpServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'checkDuplexConnection'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCheckDuplexConnectionInterceptors() -> [ServerInterceptor<LookupName, HaveDuplex>]

  /// - Returns: Interceptors to use when handling 'waitingForDuplex'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeWaitingForDuplexInterceptors() -> [ServerInterceptor<LookupName, HaveDuplex>]

  /// - Returns: Interceptors to use when handling 'getRemoteMachineInfo'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetRemoteMachineInfoInterceptors() -> [ServerInterceptor<LookupName, RemoteMachineInfo>]

  /// - Returns: Interceptors to use when handling 'getRemoteMachineAvatar'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetRemoteMachineAvatarInterceptors() -> [ServerInterceptor<LookupName, RemoteMachineAvatar>]

  /// - Returns: Interceptors to use when handling 'processTransferOpRequest'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeProcessTransferOpRequestInterceptors() -> [ServerInterceptor<TransferOpRequest, VoidType>]

  /// - Returns: Interceptors to use when handling 'pauseTransferOp'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePauseTransferOpInterceptors() -> [ServerInterceptor<OpInfo, VoidType>]

  /// - Returns: Interceptors to use when handling 'startTransfer'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStartTransferInterceptors() -> [ServerInterceptor<OpInfo, FileChunk>]

  /// - Returns: Interceptors to use when handling 'cancelTransferOpRequest'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCancelTransferOpRequestInterceptors() -> [ServerInterceptor<OpInfo, VoidType>]

  /// - Returns: Interceptors to use when handling 'stopTransfer'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStopTransferInterceptors() -> [ServerInterceptor<StopInfo, VoidType>]

  /// - Returns: Interceptors to use when handling 'ping'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePingInterceptors() -> [ServerInterceptor<LookupName, VoidType>]
}
/// To build a server, implement a class that conforms to this protocol.
public protocol WarpRegistrationProvider: CallHandlerProvider {
  var interceptors: WarpRegistrationServerInterceptorFactoryProtocol? { get }

  func requestCertificate(request: RegRequest, context: StatusOnlyCallContext) -> EventLoopFuture<RegResponse>
}

extension WarpRegistrationProvider {
  public var serviceName: Substring { return "WarpRegistration" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "RequestCertificate":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<RegRequest>(),
        responseSerializer: ProtobufSerializer<RegResponse>(),
        interceptors: self.interceptors?.makeRequestCertificateInterceptors() ?? [],
        userFunction: self.requestCertificate(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol WarpRegistrationServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'requestCertificate'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRequestCertificateInterceptors() -> [ServerInterceptor<RegRequest, RegResponse>]
}
